### ISSUE TITLE
Error validating token response: Error validating identity token: System.NotImplementedException

### ISSUE THREAD

**Issue by davideravasi** [DuendeArchive/IdentityModel.OidcClient#310]
Hello,
I have a problem with the method OidcClient.ProcessResponseAsync in the nuget version 3.1.2.
In the result that I receive in this line of code:
`var externalLoginResult = await this.oidcClient.ProcessResponseAsync(response, externalAuthorizeState);`

I have this error:

```
Error validating token response: Error validating identity token: System.NotImplementedException: The method or operation is not implemented.
  at System.Security.Cryptography.ECDsa.Create (System.Security.Cryptography.ECParameters parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/System.Core/System/Security/Cryptography/ECDsa.cs:76 
  at IdentityModel.OidcClient.IdentityTokenValidator.ValidateSignature (System.String identityToken, System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler handler, Microsoft.IdentityModel.Tokens.TokenValidationParameters parameters) [0x00129] in C:\local\identity\model\IdentityModel.OidcClient\src\IdentityTokenValidator.cs:187 
  at IdentityModel.OidcClient.IdentityTokenValidator.ValidateAsync (System.String identityToken, System.Threading.CancellationToken cancellationToken) [0x0019a] in C:\local\identity\model\IdentityModel.OidcClient\src\IdentityTokenValidator.cs:104
```

So basically, seems like that the class IdentityTokenValidator.cs does not implement a certain method but, I can't find this class in the master branch of this github repository. I saw that the IdentityTokenValidator stuff is contained in another nuget which is in preview and it's not compatible with the version 3.1.2. of OidClient.

What I'm doing wrong? The solution that I'm using contains:
IdentityModel.OidcClient 3.1.2.
System.IdentityModel.Tokens.Jwt 6.11.0.
Microsoft.Extensions.Logging 5.0.0.

Should I add more nuget packages?

The strange thing is that... with the OidcClient 2.9.1. my login works fine!

When I update the version from 2.9.1. to 3.1.2. the only thing that I'm changing is:
`TokenClientAuthenticationStyle = IdentityModel.Client.AuthenticationStyle.BasicAuthentication`
In the new version provided (Authorization Header).

Thank you in advance :)

**Comment by leastprivilege** [comment]
Well - the error is happening in 

`System.Security.Cryptography.ECDsa.Create´

Which points to some lib, framework, OS incompatibility.

Have you tried the latest preview?

**Comment by davideravasi** [comment]
I could try the latest preview but, is a preview and we have an App in prod.
So, do you think that is ok if we remain with the version 2.9.1?

In the next months we will have to migrate the App from Xamarin to MAUI or something like that and in that case we will rewrite the login (I think that implemented from scratch the version 3.1.2. has no problems).

The version 2.9.1. has security issues and is unstable for a prod app? If no we will wait to rewrite the new login in the next months.

Thank you in advance :)

**Comment by leastprivilege** [comment]
> I could try the latest preview but, is a preview and we have an App in prod.

I said *try* - not deploy ;)
